trigger: 
- main
 
pool: 
   vmImage: ubuntu-latest
 
jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: TEST
    resourceType: virtualMachine
    resourceName: TestServer01 # only deploy to the VM resource named USHAN-PC
    #tags: "service"
  strategy:
          runOnce:
            deploy:
              steps:
                - download: none